# Generated by Django 2.2 on 2020-02-25 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login_app', '0003_user_birthdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('desc', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, upload_to='quiz_banner')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('o1', models.CharField(max_length=50)),
                ('o2', models.CharField(max_length=50)),
                ('o3', models.CharField(max_length=50)),
                ('o4', models.CharField(max_length=50)),
                ('q1', models.CharField(max_length=50)),
                ('q2', models.CharField(max_length=50)),
                ('q3', models.CharField(max_length=50)),
                ('q4', models.CharField(max_length=50)),
                ('q5', models.CharField(max_length=50)),
                ('q6', models.CharField(max_length=50)),
                ('q7', models.CharField(max_length=50)),
                ('q8', models.CharField(max_length=50)),
                ('q9', models.CharField(max_length=50)),
                ('q10', models.CharField(max_length=50)),
                ('q1a1', models.CharField(max_length=50)),
                ('q1a2', models.CharField(max_length=50)),
                ('q1a3', models.CharField(max_length=50)),
                ('q1a4', models.CharField(max_length=50)),
                ('q2a1', models.CharField(max_length=50)),
                ('q2a2', models.CharField(max_length=50)),
                ('q2a3', models.CharField(max_length=50)),
                ('q2a4', models.CharField(max_length=50)),
                ('q3a1', models.CharField(max_length=50)),
                ('q3a2', models.CharField(max_length=50)),
                ('q3a3', models.CharField(max_length=50)),
                ('q3a4', models.CharField(max_length=50)),
                ('q4a1', models.CharField(max_length=50)),
                ('q4a2', models.CharField(max_length=50)),
                ('q4a3', models.CharField(max_length=50)),
                ('q4a4', models.CharField(max_length=50)),
                ('q5a1', models.CharField(max_length=50)),
                ('q5a2', models.CharField(max_length=50)),
                ('q5a3', models.CharField(max_length=50)),
                ('q5a4', models.CharField(max_length=50)),
                ('q6a1', models.CharField(max_length=50)),
                ('q6a2', models.CharField(max_length=50)),
                ('q6a3', models.CharField(max_length=50)),
                ('q6a4', models.CharField(max_length=50)),
                ('q7a1', models.CharField(max_length=50)),
                ('q7a2', models.CharField(max_length=50)),
                ('q7a3', models.CharField(max_length=50)),
                ('q7a4', models.CharField(max_length=50)),
                ('q8a1', models.CharField(max_length=50)),
                ('q8a2', models.CharField(max_length=50)),
                ('q8a3', models.CharField(max_length=50)),
                ('q8a4', models.CharField(max_length=50)),
                ('q9a1', models.CharField(max_length=50)),
                ('q9a2', models.CharField(max_length=50)),
                ('q9a3', models.CharField(max_length=50)),
                ('q9a4', models.CharField(max_length=50)),
                ('q10a1', models.CharField(max_length=50)),
                ('q10a2', models.CharField(max_length=50)),
                ('q10a3', models.CharField(max_length=50)),
                ('q10a4', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome', models.CharField(max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fuzzbeed_app.Quiz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login_app.User')),
            ],
        ),
        migrations.AddField(
            model_name='quiz',
            name='users',
            field=models.ManyToManyField(through='fuzzbeed_app.Result', to='login_app.User'),
        ),
    ]
